<!doctype html>
<html><head><meta charset="utf-8"><style>
body{font-family:DejaVu Sans,sans-serif;color:#172033;font-size:10px;margin:22px}h1{font-size:21px;margin:0;color:#4b0d44}h2{font-size:13px;margin:18px 0 7px;color:#4b0d44}.header{text-align:center;border-bottom:2px solid #b88a13;padding-bottom:12px}.school-logo-wrap{height:90px;text-align:center;margin-bottom:8px}.school-logo{width:90px;height:90px;object-fit:contain}.school{font-size:15px;font-weight:bold}.muted{color:#687386}.meta{width:100%;margin-top:14px;border-collapse:collapse}.meta td{padding:4px 7px;border:1px solid #dde2ea}.record{page-break-inside:avoid}.subjects{width:100%;border-collapse:collapse}.subjects th{background:#4b0d44;color:#fff;text-align:left;padding:6px}.subjects td{border:1px solid #d9dee7;padding:5px}.summary{background:#fff7dc;padding:7px;margin-top:5px}.footer{margin-top:20px;border-top:1px solid #d9dee7;padding-top:8px;color:#687386;text-align:center}
</style></head><body>
<div class="header">@if($logoBase64)<div class="school-logo-wrap"><img class="school-logo" src="{!! $logoBase64 !!}" width="90" height="90" alt="School logo"></div>@endif<div class="school">{{ $school?->school_name ?? 'School Academic Transcript' }}</div><div>{{ $school?->address }}</div><h1>OFFICIAL STUDENT TRANSCRIPT</h1>@if($term)<div>{{ $term }}</div>@else<div>All terms</div>@endif</div>
<table class="meta"><tr><td><strong>Student</strong><br>{{ trim($student->surname.' '.$student->firstname.' '.$student->third_name) }}</td><td><strong>Admission No.</strong><br>{{ $student->reg_no ?: 'N/A' }}</td></tr><tr><td><strong>Current class</strong><br>{{ $student->level?->name ?: 'N/A' }}</td><td><strong>Student status</strong><br>{{ ucfirst($student->student_status ?: 'active') }}</td></tr></table>
@foreach($records as $record)
<div class="record"><h2>{{ $record['session'] }} — {{ $record['term'] }} · {{ $record['class_name'] ?: 'Class not recorded' }}</h2>
<table class="subjects"><thead><tr><th>Subject</th><th>CA</th><th>Exam</th><th>Total</th><th>Grade</th><th>Remark</th></tr></thead><tbody>
@foreach($record['subjects'] as $subject)<tr><td>{{ $subject['name'] }}</td><td>{{ $subject['ca'] }}</td><td>{{ $subject['exam'] }}</td><td>{{ $subject['total'] }}</td><td>{{ $subject['grade'] }}</td><td>{{ $subject['remark'] }}</td></tr>@endforeach
</tbody></table><div class="summary"><strong>Term average:</strong> {{ $record['average'] ?? 'N/A' }} &nbsp; <strong>Overall grade:</strong> {{ $record['grade'] ?? 'N/A' }} &nbsp; <strong>Position:</strong> {{ $record['position'] ?? 'N/A' }}</div></div>
@endforeach
<div class="footer">Generated by GradeQuest on {{ $generated_at->format('d M Y, h:i A') }}. This transcript contains published school results only.</div>
</body></html>
